matrix:
  user_id: "@bot:example.org"
  user_password: "change_this"
  homeserver_url: https://example.org
  device_id: ABCDEFGHIJ
  device_name: aaaalter_matrix

storage:
  database: "sqlite://bot.db"
  store_path: "./store"

logging:
  level: INFO
  file_logging:
    enabled: false
    filepath: bot.log
  console_logging:
    enabled: true
